python 1.w2c_model_start.py	
python 2.w2c_model_close.py	
python 3.w2c_model_all.py	
python 3.device_quchong_start_app_w2c.py
python 3.w2c_all_emb.py
python 4.device_age_prob_oof.py	
python 5.device_sex_prob_oof.py	
python 6.start_close_age_prob_oof.py	
python 7.start_close_sex_prob_oof.py	
python 9.sex_age_bin_prob_oof.py	
python 10.age_bin_prob_oof.py	
python 11.hcc_device_brand_age_sex.py	 
python 12.device_age_regression_prob_oof.py	
python 13.device_start_GRU_pred.py		
python 14.device_start_GRU_pred_age.py		
python 15.device_all_GRU_pred.py	
python 16.device_start_capsule_pred.py		
python 17.device_start_textcnn_pred.py		
python 18.device_start_text_dpcnn_pred.py	
python 19.device_start_lstm_pred.py	
python 20.lgb_sex_age_prob_oof.py		
python 21.tfidf_lr_sex_age_prob_oof.py	
python 22.base_feat.py		
python 23.ATT_v6.py	
python 24.thluo_22_lgb.py	
python 25.thluo_22_xgb.py	
python 26.thluo_nb_lgb.py	
python 27.thluo_nb_xgb.py	
python 28.final.py	 	